### ISSUE TITLE
Explore and Implement Model Extraction Attacks and Defences

### ISSUE THREAD

**Issue by beat-buesser** [Trusted-AI/adversarial-robustness-toolbox#191]
The main goal of this issue is to define an epic aiming to extend ART with Model Extraction Attacks and Defences. This will introduce a new class of tools for ART that can test and defend trained and deployed models against model extraction. Here we are collecting references of possible candidates for implementation and their general discussion.

Proposals based on references in Jagielski et al. (https://arxiv.org/abs/1909.01838):

## Attacks
- [ ] Lowd and Meek, https://ix.cs.uoregon.edu/~lowd/kdd05lowd.pdf
- [ ] Tramer et al., https://arxiv.org/abs/1609.02943,  (Active) Learning
- [ ] Tramer et al., https://arxiv.org/abs/1609.02943,  Path finding
- [ ] Milli et al., https://arxiv.org/abs/1807.05185, (theoretical) Direct Recovery
- [ ] Milli et al., https://arxiv.org/abs/1807.05185, Learning
- [ ] Pal et al., https://arxiv.org/abs/1905.09165, Active learning
- [ ] Chandrasekharan et al., https://arxiv.org/abs/1811.02054, Active learning
- [x] Copycat CNN, https://arxiv.org/abs/1806.05476, Learning (#229)
- [ ] Papernot et al., https://arxiv.org/abs/1602.02697, Active learning
- [ ] CSI NN, https://arxiv.org/abs/1810.09076, Direct Recovery
- [x] Knockoff Nets, https://arxiv.org/abs/1812.02766, Learning (#230)
- [x] Jagielski et al., https://arxiv.org/abs/1909.01838, Functionally equivalent (#216) 
- [ ] Jagielski et al., https://arxiv.org/abs/1909.01838, Direct Recovery

## Defences (#233)
- [x] only high probability classes
- [x] class labels
- [x] reverse sigmoid
- [x] rounding to precision
- [x] random noise
- [ ] sample model parameters

**Comment by beat-buesser** [comment]
I have created branch `development_extraction` for this epic.

**Comment by TS-Lee** [comment]
I should have implementations of ...
- Papernot et al., https://arxiv.org/abs/1602.02697, Active learning
- Tramer et al., https://arxiv.org/abs/1609.02943 --> attack against general model querying samples and training a model from the result.
- updating...

**Comment by minhitbk** [comment]
So then I work on KnockoffNets and CopyCatCNN.

**Comment by nguyenvulong** [comment]
This paper links to Milli et al. (The author also coworked with Papernot) 
https://www.usenix.org/system/files/sec20-jagielski.pdf
